### ISSUE TITLE
vCard not found "404"

### ISSUE THREAD

**Issue by UweBerlin** [Metric/CardDavNet#9]
Hi,
i try to access my posteo.de carddav server.
Access seems to work.

CardDavResponse response = _client.Get();
in resonse ic can see al my entries, but :
foreach (CardElement el in response.Cards)
{
    string id = el.Id;
    vCard card = _client.GetVCard(id);
}
this brings System.Net.WebException: "Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden."

if i use:
vCard card = _client.GetVCard(response.Cards.First().Id);
this also brings System.Net.WebException: "Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden."

I changed a bit in client.cs as a Try:
public bool CanConnect()
{
    Dictionary<string, string> results = this.Query(this.serverUrl, "OPTIONS");

    if (results.ContainsKey("status"))
    {
        string status = results["status"];

        if (status.Equals("200") || status.Equals("OK"))
            return true;
    }

    return false;
}

Any idea what could be wrong in my program ?

Regards Uwe

**Comment by UweBerlin** [comment]
Solved the problem !
the Posteo.de CardDav needs the Id with .vcf, so i use the CardElement.DavName member and that works fine.
The changes i made in CanConnect() (see above) must stay because the the Posteo.de CardDav Server returns "OK".

**Comment by Metric** [comment]
Pushed the CanConnect changes for "OK", since I never got a Pull request for it.
